### PR TITLE
feat: climate entity support for metric/imperial

### PR DESCRIPTION
**Pull request by martonborzak**
Adding support for metric and imperial systems to show temperatures in `ºC` or `ºF`

### CODE REVIEW

**Review by zehnm — COMMENTED** [review]
How does the unit system work?
Is it completely controlled by the integration or can it be set on the remote on a global level?
I don't see any unit conversion, that's why I'm asking. If it's set globally, then we need conversion functionality if the integration is not able to handle it and only provides metric or imperial values.

**Comment by martonborzak** [comment]
It is set globally. I don't know if all integrations could provide information about the units. Some are just pushing data.

**Review by zehnm — APPROVED** [review]
> It is set globally. 

In this case the setting is more of cosmetic nature displaying the values of the integrations.
Then let's trust the integrations providing the correct unit :-)

**Comment by martonborzak** [comment]
We can always do some checks, like 60ºC is highly unlikely for room temperature, unless there's a fire :)

**Pull request merged**
