### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by martonborzak**

### CODE REVIEW

**Review by carp3-noctem — APPROVED** [review]

**Review by zehnm — APPROVED** [review]
Looks good, we just have to come up with some text for feature requests in a timely manner.

**Comment by martonborzak** [comment]
> Looks good, we just have to come up with some text for feature requests in a timely manner.

Let's add this and then we merge. @nklerk @carp3-noctem

**Comment by zehnm** [comment]
Do we also need a Code of Conduct?
E.g. something like https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by zehnm** [comment]
Suggestion for the missing 'Feature Request' section - taken from: https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#feature-requests

> Feature requests are welcome. But take a moment to find out whether your idea fits with the scope and aims of the project. It's up to you to make a strong case to convince the project's developers of the merits of this feature. Please provide as much detail and context as possible.

Then we should probably link https://community.yio-remote.com/c/feature-requests and decide if the forum or GitHub is the main place for feature requests. Coordinating two places creates too much work! My suggestion:
- Forum: discuss ideas and voting
- GitHub: concrete requests with detailed informations on how to develop it.

BUT this means we'd have to reject requests which haven't been discussed yet in the forum!? Also not very user friendly...
What are you thinking @martonborzak @carp3-noctem @nklerk ?

**Comment by martonborzak** [comment]
I think it makes sense what you are proposing @zehnm. Forum for discussing ideas and github for the actual request that goes into the backlog. We shouldn't reject ideas because they were not discussed on the forum. I think we should be flexible about this.

**Comment by martonborzak** [comment]
Added the feature request part, based on what you had there. I'll merge this and we can always add stuff to it later. Any objections? @zehnm @carp3-noctem @nklerk

**Pull request merged**
