### PR TITLE
Lot of changes, including enums, plugin interfaces

### PR DESCRIPTION
**Pull request by martonborzak**

### CODE REVIEW

**Comment by martonborzak** [comment]
@ChristianRiedl I went through all the conflicts and corrected them so I think it will work. Would you also take a look at comment on the lines that you think is problematic?

Regarding the mediaplayer entity `browseResultChanged` signal: It needs to emit the model as well to support multi-level browsing. The UI catches that model and creates a page for it. Then you go deeper in the level and you create a new model for the next level. Send it to the UI, etc.

**Comment by ChristianRiedl** [comment]
@marton from my view browseResult was the attribute I used to deliver the browwse results as QVariantList. Then we switched to the QAbstractListModel. In the interface we have now a **setSearchModel** fireing **searchModelChanged** and **setBrowseModel** fireing **browseModelChanged**. I did not find the place where it is emitted so I thought it is not required any more.

**Comment by martonborzak** [comment]
> @marton from my view browseResult was the attribute I used to deliver the browwse results as QVariantList. Then we switched to the QAbstractListModel. In the interface we have now a **setSearchModel** fireing **searchModelChanged** and **setBrowseModel** fireing **browseModelChanged**. I did not find the place where it is emitted so I thought it is not required any more.

No problem. The signal is caught in the UI.

**Comment by ChristianRiedl** [comment]
@marton But why is **browseModel** handled different than **searchModel**. Both are QML properties with a changed signal. Why requires **browseModelChanged** the model as parameter when the model is a property of the object.

**Comment by martonborzak** [comment]
> @marton But why is **browseModel** handled different than **searchModel**. Both are QML properties with a changed signal. Why requires **browseModelChanged** the model as parameter when the model is a property of the object.

The UI is dynamically adding new pages as you browse more so for example:
First step is list of artists. Then you click on one and you get a list of albums of that artist. Then you go to one album. For each of these changes we need a browseModel. If the mediaplayer object has only one then the UI will bind to that. Rather I decided to emit the model with the signal that can be caught by the UI and assigned to the dynamically created page.

An other thing @ChristianRiedl. I have merged the code, but I am getting compile errors:
`Undefined symbols for architecture x86_64:
  "typeinfo for IntegrationInterface", referenced from:
      typeinfo for Integration in moc_integration.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../binaries/osx-clang-x64/debug/remote.app/Contents/MacOS/remote] Error 1
11:15:49: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project remote (kit: Desktop Qt 5.12.4 clang 64bit)
When executing step "Make"`

Would you be able to look at the code in *dev branch*?

**Comment by ChristianRiedl** [comment]
@marton 
browseModel is clear now. I do not get an error when compiling remote-software dev after 
makeing some changes (signalnames) in config.h and repairing BROWSERESULT

    Q_PROPERTY (QVariantMap      config         READ config               WRITE setConfig       NOTIFY configChanged)
    Q_PROPERTY (QString          profile        READ profile              WRITE setProfile      NOTIFY profileChanged)
    Q_PROPERTY (QVariantMap      settings       READ getSettings          WRITE setSettings     NOTIFY settingsChanged)
    Q_PROPERTY (QVariantMap      integrations   READ getIntegrations                            CONSTANT)
    Q_PROPERTY (QVariantMap      entities       READ getAllEntities                             CONSTANT)
    Q_PROPERTY (QVariantMap      profiles       READ getProfiles                                NOTIFY profilesChanged)
    Q_PROPERTY (QVariantMap      ui_config      READ getUIConfig                                NOTIFY uiConfigChanged)
    Q_PROPERTY (QVariantMap      pages          READ getPages                                   NOTIFY pagesChanged)
    Q_PROPERTY (QVariantMap      groups         READ getGroups                                  NOTIFY groupsChanged)

Maybe it is required to execute **qmake**. Maybe it helps to remove integration.h from the remote.pro file. Integration.h should not be used inside remote.

**Comment by ChristianRiedl** [comment]
@marton some small things should be corrected in integrations.h
(add **Q_INTERFACES** and remove **CONSTANT**)

    class Integrations : public QObject, IntegrationsInterface
    {
        Q_OBJECT
        Q_INTERFACES(IntegrationsInterface)
    
    public:
        // list of all integrations
        Q_PROPERTY  (QList<QObject *>       list         READ    list NOTIFY     listChanged)

In touchdetect.h and proximity_gesture_control.h are properies defined with "NOTIFY" but without READ. I get a warning that its invalid.

In notifications.h CONSTANT shall be removed from the properties.

**Comment by ChristianRiedl** [comment]
In touchdetect you want to create a detectedChangedEvent whenever you get  a TouchBegin or MouseButtonPressed. I propose to make a int detected property which is incremented .

    Q_PROPERTY(int detected READ detected NOTIFY detectedChanged)
    public:
    TouchEventFilter()
    {
        m_detected = 0;
        m_source = nullptr;
    }
    int detected() { return m_detected; }
    private:
    bool eventFilter(QObject *obj, QEvent *event)
    {
        Q_UNUSED(obj)
        switch (event->type()) {
        case QEvent::TouchBegin:
        case QEvent::MouseButtonPress:
            m_detected++;
            emit detectedChanged();
            break;

**Comment by martonborzak** [comment]
Thanks @ChristianRiedl! Removing `integration.h` did the trick.

I have went through the code and replaced `supported_features.indexOf` with `obj.isSupported`. Also fixed some UI glitches that the new update caused.

Fixed also the 2 warnings about the missing READ.

For the touchdetect, right now it's not relevant to know how many times there was an event. But feel free to create a feature branch with this suggestion.

Also I think it's a good time now to review the code and do a little bit of cleanup. What do you think?

**Comment by ChristianRiedl** [comment]
@marton I proposed detected count not because counting it is required, but because it is the clean way to provide the detectedChanged with the **Q_PROPERTY detected**. I get a compile warning that **a property with NOTIFY and without READ is invalid**. So there must be some detected() function.
When we use a boolean it never changes because it is not reset. So m_detected++ changes detected everytime when detectedChanged is called.  And this is good for QML.

I will now try to make ROON work with the new QML views. But before I will create some **developing integrations**  page in the Wiki explaining the things I introduced for the integrations
and some "performance" recommendations. And I will update the entities wiki. OK ?

**Comment by martonborzak** [comment]
> @marton I proposed detected count not because counting it is required, but because it is the clean way to provide the detectedChanged with the **Q_PROPERTY detected**. I get a compile warning that **a property with NOTIFY and without READ is invalid**. So there must be some detected() function.
> When we use a boolean it never changes because it is not reset. So m_detected++ changes detected everytime when detectedChanged is called. And this is good for QML.
> 
> I will now try to make ROON work with the new QML views. But before I will create some **developing integrations** page in the Wiki explaining the things I introduced for the integrations
> and some "performance" recommendations. And I will update the entities wiki. OK ?

I get it. I added a detected() that returns true; I know it's a dirty fix but it works :)
Of course it's OK with the Wiki!
I have more tasks with the MediaPlayer UI, but that should not really influence the ROON backend.

**Comment by ChristianRiedl** [comment]
@marton I don't know where is the best place to discuss the "cleanup" things.

One thing I noticed. I wonder why ContextMenu.qml is situated in basic_ui as it is completly media_player specific. 

But anyhow it should be more generic. We should avoid the requirement to add a new function to the mediaplayer entity when a new play command is required.  It should be determinded by the integration. Partially it is solved as the integration provides the play command (PLAY, QUEUE). 
I think we should have **one playMedia** and add command as third parameter. Than we do not need **addToQueue** and **songRadio** functions. Remains the **text** and the **icon**.

The text could be solved to use "Add to Queue" instead of "QUEUE"  command. But maybe it could be handled with the translations, translating "QUEUE" to "Add to Queue". But I do not really understand the translation feature. The icon is remaining problem. 

Maybe we add a function to the mediaplayentity, where the integration can set a list of play commands including readable text, icon, (translation ?).  

You are currently the "owner" of the dev branches. It is easy for you to make the playMedia changes with command as 3. parameter. I think we make nothing wrong.

**Pull request merged**
